blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/sas-technology/sas-default-app/discussions
    about: Ask questions, share ideas, or get help from the community
